In [1]:
from Data.Dataset import getDataset

gen = getDataset(0.1)
print(gen)

2023-08-14 05:57:32.626362: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-14 05:57:32.677876: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-14 05:57:33.420276: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-08-14 05:57:34.446557: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at http

(<_FlatMapDataset element_spec=(TensorSpec(shape=(5000, 12), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.float32, name=None))>, <_FlatMapDataset element_spec=(TensorSpec(shape=(5000, 12), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.float32, name=None))>)


2023-08-14 05:57:34.485821: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-14 05:57:34.487424: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-14 05:57:34.490023: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [2]:
a = gen[0].batch(32)

for b in a:
    print(b)
    break

(<tf.Tensor: shape=(32, 5000, 12), dtype=float32, numpy=
array([[[   -9.,  -585.,    58., ...,   297.,   283.,  -580.],
        [   -9.,  -585.,    58., ...,   297.,   283.,  -580.],
        [   -9.,  -585.,    58., ...,   297.,   283.,  -580.],
        ...,
        [  -92.,   488.,   551., ...,  -198.,  -336.,   534.],
        [  -92.,   473.,   566., ...,  -190.,  -328.,   519.],
        [ -102.,   439.,   575., ...,  -168.,  -321.,   490.]],

       [[  -48.,    -9.,   605., ...,    28.,   -43.,    15.],
        [  -48.,    -9.,   605., ...,    28.,   -43.,    15.],
        [  -48.,    -9.,   605., ...,    28.,   -43.,    15.],
        ...,
        [   -9.,    58., -1063., ...,   -24.,   -38.,    62.],
        [    0.,    34., -1058., ...,   -17.,   -17.,    34.],
        [    9.,    19., -1054., ...,   -14.,     0.,    14.]],

       [[    0.,   -29.,   312., ...,    14.,    14.,   -29.],
        [    0.,   -29.,   312., ...,    14.,    14.,   -29.],
        [    0.,   -29.,   312.

In [3]:
a = gen.to_numpy()

NameError: name 'gen' is not defined

In [5]:
print(a.shape)

(5000, 12)


In [2]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 2.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 75.4 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 28.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 100.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 104.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 64.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.6/311.6 kB 41.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 97.8 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 108.2 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 32.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 13.3 MB/s eta 0:

  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.2
    Uninstalling protobuf-3.20.2:
      Successfully uninstalled protobuf-3.20.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sagemaker 2.126.0 requires protobuf<4.0,>=3.1, but you have protobuf 4.24.0 which is incompatible.


In [4]:
from Data.Dataset import getDatasetGenerator
import pandas as pd

csv = pd.read_csv(dirs)
gg = getDatasetGenerator(csv, dir_)
for i in gg:
    print(i)
    break

tf.Tensor(
[[  -9. -585.   58. ...  297.  283. -580.]
 [  -9. -585.   58. ...  297.  283. -580.]
 [  -9. -585.   58. ...  297.  283. -580.]
 ...
 [ -92.  488.  551. ... -198. -336.  534.]
 [ -92.  473.  566. ... -190. -328.  519.]
 [-102.  439.  575. ... -168. -321.  490.]], shape=(5000, 12), dtype=float32) 1.0
(<tf.Tensor: shape=(5000, 12), dtype=float32, numpy=
array([[  -9., -585.,   58., ...,  297.,  283., -580.],
       [  -9., -585.,   58., ...,  297.,  283., -580.],
       [  -9., -585.,   58., ...,  297.,  283., -580.],
       ...,
       [ -92.,  488.,  551., ..., -198., -336.,  534.],
       [ -92.,  473.,  566., ..., -190., -328.,  519.],
       [-102.,  439.,  575., ..., -168., -321.,  490.]], dtype=float32)>, 1.0)


In [1]:
import tensorflow as tf

def datagen(shape, y):
    data = tf.random.uniform(shape)
    for i in range(10):
        yield data, y
        
size = [2, 3]

dataset = tf.data.Dataset.from_generator(
    datagen,
    output_signature=(
        tf.TensorSpec(shape=size, dtype=tf.float32),
        tf.TensorSpec(shape=(), dtype=tf.float32)
    ),
    args=(size, 3)
)

for i, data in enumerate(dataset.batch(4)):
    print(data)
    if i == 2:
        break

2023-08-15 12:52:52.367056: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-15 12:52:52.418695: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-15 12:52:53.243614: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-08-15 12:52:54.502966: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at http

(<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]],

       [[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]],

       [[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]],

       [[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]]], dtype=float32)>, <tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 3., 3.], dtype=float32)>)
(<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]],

       [[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]],

       [[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]],

       [[0.93356097, 0.35017335, 0.3131076 ],
        [0.80464005, 0.4721061 , 0.76046073]]], dtype=float32)>, <tf.Tensor: shape=(4,), 

s-bus-pci#L344-L355
2023-08-15 12:52:54.551234: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-15 12:52:54.553104: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-15 12:52:55.331676: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentat

In [5]:
from keras import layers, Model

class dd(Model):
    def __init__(self):
        super().__init__()
        self.bn = layers.BatchNormalization()
        
    def call(self, x):
        return self.bn(x)
    
dj = dd()
for d in dataset.batch(4):
    print(dj(d[0]))

tf.Tensor(
[[[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]

 [[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]

 [[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]

 [[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]], shape=(4, 2, 3), dtype=float32)
tf.Tensor(
[[[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]

 [[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]

 [[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]

 [[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]], shape=(4, 2, 3), dtype=float32)
tf.Tensor(
[[[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]

 [[0.9386937  0.41475663 0.905205  ]
  [0.6664013  0.36811092 0.14399697]]], shape=(2, 2, 3), dtype=float32)


In [ ]:
#%%
import tensorflow as tf

x = tf.cast([[[[[1]]]]], tf.int32)
y = x
x += 1

print(x, y)

# %%
import tensorflow as tf
from keras import layers, Model

class testtt(Model):
    def __init__(self):
        super().__init__()
        # self.layer = layers.BatchNormalization()
        # self.layer2 = layers.LayerNormalization(epsilon=0.00001)
        # self.relu = layers.ReLU()
        self.dropout = layers.Dropout(rate=0.5)
    
    def call(self, x):
        # x = self.layer(x, training=True)
        # x = self.layer2(x)
        # x = self.relu(x)
        x = self.dropout(x)
        return x
    
j = testtt()
i = tf.random.uniform([5, 32, 32, 3])
i = tf.random.uniform([3, 2])
ans = tf.zeros([3, 2])
opt = tf.optimizers.SGD()
print(i)
print(j(i))
# printweight(j.weights)
# j.compile(optimizer="sgd", loss="mse")
# j.fit(i, ans, epochs=2)

# with tf.GradientTape() as tape:
#     k = j(i)
#     loss = tf.losses.mean_squared_error(k, ans)
# grad = tape.gradient(loss, j.trainable_weights)
# opt.apply_gradients(zip(grad, j.trainable_weights))
# print(k)

def printweight(weight):
    print("##")
    for w in weight:
        print(w)

printweight(j.weights)
printweight(j.trainable_weights)

# %%
import torch
layer = torch.nn.BatchNorm1d(2)
x = torch.rand([2, 3, 3])
y = layer(x)
print(x)
print(y)

# %%
import numpy as np
a = np.random.random([4, 5, 6])
for i in a:
    print(i)
# %%

def jj(a, b, c):
    print(a+b+c)

def jojo(d, **kwargs):
    print(d)
    jj(**kwargs)

dic = {'a':1, 'b':2, 'c':4, 'd':8}

jojo(**dic)
# %%

In [4]:
import numpy as np


np.mean([3, 4])

3.5

In [22]:
import tensorflow as tf

a = [2]
a = tf.cast(a, tf.float32)
a = float(a)
print(a + a)

4.0


In [23]:
!python train.py

2023-08-14 08:32:20.499494: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-14 08:32:20.549641: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-14 08:32:21.214739: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-08-14 08:32:22.430982: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at http

In [1]:
a = []

In [5]:
import tensorflow as tf
import numpy as np

a = []
b = tf.cast([3, 4], tf.float32)
a.append(b)
a.append(b)
print(a)

[<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>]
